apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "datadogcurryware-deployment"
  labels:
    app: "datadogcurryware"
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "chuckjoke-frontend"
    tags.datadoghq.com/version: "0.2.8"
    admission.datadoghq.com/enabled: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "datadogcurryware"
      tags.datadoghq.com/env: "prod"
      tags.datadoghq.com/service: "chuckjoke-frontend"
      tags.datadoghq.com/version: "0.2.8"
  template:
    metadata:
      labels:
        app: "datadogcurryware"
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "chuckjoke-frontend"
        tags.datadoghq.com/version: "0.2.8"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/python-lib.version: "v1.12.0"
    spec:
      containers:
        - name: "datadogcurryware"
          image: "scotcurry4/datadogcurryware:latest"
          ports:
            - containerPort: 8088
          env:
            - name: DD_LOGS_INJECTION
              value: 'true'
            # This environment variable is so log formatting is correct in the containerized scenarios.
            - name: RUN_LOCAL
              value: 'false'