apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadogcurryware-deployment
  labels:
    app: datadogcurryware
    tags.datadoghq.com/env: prod
    tags.datadoghq.com/service: chuckjoke-frontend
    tags.datadoghq.com/version: 0.2.8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadogcurryware
  template:
    metadata:
      labels:
        app: datadogcurryware
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/service: chuckjoke-frontend
        tags.datadoghq.com/version: 0.2.8
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/python-lib.version: v1.6.3
        ad.datadoghq.com/datadogcurryware.logs: '[{"source": "python", "service": "chuckjoke-frontend"}]'
    spec:
      containers:
        - name: datadogcurryware
          image: docker.io/scotcurry4/datadogcurryware:latest
          ports:
            - containerPort: 8088
          env:
            - name: DD_LOGS_INJECTION
              value: 'true'
            # This environment variable is so log formatting is correct in the containerized scenarios.
            - name: RUN_LOCAL
              value: 'false'