apiVersion: v1
kind: Service
metadata:
  name: datadogcurryware-service
spec:
  type: LoadBalancer
  selector:
    app: datadogcurryware
  ports:
    - name: "http"
      protocol: "TCP"
      port: 8088
      targetPort: 8088
      nodePort: 30005