apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadogcurryware-deployment
  labels:
    app: datadogcurryware
    tags.datadoghq.com/env: curryware-minikube
    tags.datadoghq.com/service: curryware-frontend
    tags.datadoghq.com/version: 0.2.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datadogcurryware
  template:
    metadata:
      labels:
        app: datadogcurryware
        tags.datadoghq.com/env: curryware-minikube
        tags.datadoghq.com/service: curryware-frontend
        tags.datadoghq.com/version: 0.2.0
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/python-lib.version: v1.6.3
    spec:
      containers:
        - name: datadogcurryware
          image: docker.io/scotcurry4/datadogcurryware:0.2.0
          ports:
            - containerPort: 8088
          env:
            - name: DD_LOGS_INJECTION
              value: 'true'