version: '3.8'
services:
  datadogcurryware:
    image: scotcurry4/datadogcurryware:latest
    container_name: datadogcurryware
    ports:
      - "8088:8088"
    #  There is a way to ingest labels and make the tags.  Need to look into this.
    labels:
      com.datadoghq.tags.build: '3.704.1123'
      # Unified Tagging items
      com.datadoghq.tags.env: 'staging'
      com.datadoghq.tags.service: 'chuckjoke-frontend'
      com.datadoghq.tags.version: '3.704.1123'
      com.datadoghq.tags.labeltag: 'added-label-tag'
      # This line is what will add the source tag.  That tag is used to make sure the right log pipeline is used.
      # Need to research this to figure out which takes precedent (env or labels).
      com.datadoghq.ad.logs: '[{"source": "python", "service": "chuckjoke-frontend"}]'
      org.opencontainers.image.revision: '28ad1fa183eb40016391a4061b0c162a04e5c42a'
      org.opencontainers.image.source: 'https://github.com/scotcurry/Datadog'
    environment:
      - DD_ENV=prod
      - DD_VERSION=3.704.780
      - DD_SERVICE=chuckjoke-frontend
      - DD_LOGS_INJECTION=true
      - DD_TRACE_SAMPLE_RATE=1
      - DD_AGENT_HOST=datadog-agent
      - RUN_LOCAL=false
  agent:
    image: "datadog/agent:latest"
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_DOCKER_LABELS_AS_TAGS={"my.custom.label.team":"team"}
      - DD_HOSTNAME=docker-agent
    ports:
      - 127.0.0.1:8126:8126/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    labels:
      com.datadoghq.ad.logs: '[{"source": "datadog-agent", "service": "agent"}]'