version: '3.8'
services:
  datadogcurryware:
    image: scotcurry4/datadogcurryware:latest
    container_name: datadogcurryware
    ports:
      - "8088:8088"
    #  There is a way to ingest labels and make the tags.  Need to look into this.
    labels:
      com.datadoghq.tags.build: '3.726.760'
      # Unified Tagging items
      com.datadoghq.tags.env: 'prod'
      com.datadoghq.tags.service: 'chuckjoke-frontend'
      com.datadoghq.tags.version: '3.726.760'
      com.datadoghq.tags.labeltag: 'added-label-tag'
      org.opencontainers.image.revision: '818aafb6ea33ecbf264359d2984c59e7925778f4'
      org.opencontainers.image.source: 'github.com/scotcurry/Datadog'
      # This line is what will add the source tag.  That tag is used to make sure the right log pipeline is used.
      # Need to research this to figure out which takes precedent (env or labels).
      com.datadoghq.ad.logs: >- 
        [{
          "source": "python", 
          "service": "chuckjoke-frontend",
          "log_processing_rules": [{
            "type": "multi_line",
            "name": "log_start_with_date_time",
            "pattern": "\\d{4}-\\d{2}-\\d{2}\\s\\d{2}:\\d{2}:\\d{2},\\d{3}"
          }]
        }]
    environment:
      - DD_ENV=prod
      - DD_VERSION=3.726.760
      - DD_SERVICE=chuckjoke-frontend
      - DD_LOGS_INJECTION=true
      - DD_TRACE_SAMPLE_RATE=1
      - DD_AGENT_HOST=datadog-agent
      - RUN_LOCAL=false
      - DD_GIT_COMMIT_SHA=818aafb6ea33ecbf264359d2984c59e7925778f4
      - DD_GIT_REPOSITORY_URL=github.com/scotcurry/Datadog
  agent:
    image: "datadog/agent:latest"
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_DOCKER_LABELS_AS_TAGS={"my.custom.label.team":"team"}
      - DD_HOSTNAME=docker-agent
      - DD_REMOTE_CONFIGURATION_ENABLED=true
      - DD_INVENTORIES_CONFIGURATION_ENABLED=true
    ports:
      - 127.0.0.1:8126:8126/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    labels:
      com.datadoghq.ad.logs: '[{"source": "datadog-agent", "service": "agent"}]'