version: '3.8'
services:
  datadog:
    image: scotcurry4/datadogcurryware:0.1.0
    container_name: datadogcurryware
    ports:
      - "8088:8088"
    labels:
      com.curryware.tags.build: '0.1.0'