 # This information is based on this file https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml
 datadog:
    apiKeyExistingSecret: datadog-secret
    appKeyExistingSecret: datadog-secret
    # GKE does not accept dots (.), so default to not using them.
    clusterName: datadogcurryware-cluster
    loglevel: debug
    kubelet:
      tlsVerify:  false

    apm:
      portEnabled: true

    admissionController:
      enabled: true
      mutatedUnlabelled: true

    logs:
      enabled: true
      containerCollectAll: true

    processAgent:
      enabled: true
      processCollection: true
      processDiscovery: true
    networkMonitoring:
      enabled: false
    serviceMonitoring:
      enabled: false
