name: Datadog Curryware Build
on:
  push:
    branches:
      - 'master'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get-Source
        uses: actions/checkout@v3
      - name: Install-Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'
            cache: 'pip'
      - name: Upgrade-pip
        run: python -m pip install --upgrade pip
      - name: Install-requirements
        run: pip install -r requirements.txt
      - name: Datadog Agent
        uses: Datadog/agent-github-action@v1
        with:
          api_key: ${{ secret.DD_API_KEY }}
        run: DD_ENV=ci DD_SERVICE=chuckjoke-frontend pytest ./unittests/* --ddtrace
  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Get-Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Containers/Dockerfile
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/datadogcurryware:0.2.${{ github.run_number }},${{ secrets.DOCKER_USERNAME }}/datadogcurryware:latest
